package com.mynote;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableScheduling//告诉Spring我的项目里有用 @Scheduled 写的定时任务，请帮我跑起来
@EnableAsync      // 开启异步
public class MyNoteApplication {

    public static void main(String[] args) {
        SpringApplication.run(MyNoteApplication.class, args);
    }

}
